import {
  Budget,
  Category,
  Transaction,
  UserDashboardSummary,
  UserProfile,
  Wallet,
} from "@/lib/types";

const now = new Date();

export const mockUser: UserProfile = {
  id: "user-demo-001",
  email: "vinh@example.com",
  displayName: "Vinh Nguyễn",
  photoURL: "/avatar-demo.png",
  defaultCurrency: "VND",
  locale: "vi-VN",
  timezone: "Asia/Ho_Chi_Minh",
  status: "active",
  createdAt: now,
  updatedAt: now,
};

export const mockWallets: Wallet[] = [
  {
    id: "wallet-cash",
    userId: mockUser.id,
    name: "Tiền mặt",
    type: "cash",
    currency: "VND",
    initialBalance: 5_000_000,
    currentBalance: 4_250_000,
    color: "#003297",
    icon: "payments",
    isDefault: true,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "wallet-bank",
    userId: mockUser.id,
    name: "Tài khoản ngân hàng",
    type: "bank",
    currency: "VND",
    initialBalance: 20_000_000,
    currentBalance: 20_250_000,
    color: "#006c49",
    icon: "account_balance",
    isDefault: false,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat-food",
    userId: mockUser.id,
    name: "Ăn uống",
    kind: "expense",
    icon: "restaurant",
    color: "#764900",
    isSystem: true,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cat-transport",
    userId: mockUser.id,
    name: "Di chuyển",
    kind: "expense",
    icon: "directions_car",
    color: "#254bb3",
    isSystem: true,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cat-salary",
    userId: mockUser.id,
    name: "Lương tháng",
    kind: "income",
    icon: "account_balance_wallet",
    color: "#006c49",
    isSystem: true,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-food-001",
    userId: mockUser.id,
    walletId: "wallet-cash",
    categoryId: "cat-food",
    type: "expense",
    amount: 120_000,
    currency: "VND",
    title: "Ăn uống",
    note: "Bữa trưa văn phòng",
    occurredAt: new Date("2026-04-27T12:30:00+07:00"),
    status: "completed",
    tags: ["daily", "food"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "txn-transport-001",
    userId: mockUser.id,
    walletId: "wallet-cash",
    categoryId: "cat-transport",
    type: "expense",
    amount: 50_000,
    currency: "VND",
    title: "Di chuyển",
    note: "Grab đi làm",
    occurredAt: new Date("2026-04-27T08:15:00+07:00"),
    status: "completed",
    tags: ["transport"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "txn-salary-001",
    userId: mockUser.id,
    walletId: "wallet-bank",
    categoryId: "cat-salary",
    type: "income",
    amount: 15_000_000,
    currency: "VND",
    title: "Lương tháng",
    note: "Lương tháng 04/2026",
    occurredAt: new Date("2026-04-26T15:00:00+07:00"),
    status: "completed",
    tags: ["salary"],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockBudgets: Budget[] = [
  {
    id: "budget-food-monthly",
    userId: mockUser.id,
    name: "Ăn uống tháng này",
    categoryId: "cat-food",
    amountLimit: 4_000_000,
    amountSpent: 1_250_000,
    currency: "VND",
    period: "monthly",
    startDate: new Date("2026-04-01T00:00:00+07:00"),
    endDate: new Date("2026-04-30T23:59:59+07:00"),
    alertThresholdPercent: 80,
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockDashboardSummary: UserDashboardSummary = {
  totalBalance: mockWallets.reduce((sum, wallet) => sum + wallet.currentBalance, 0),
  todayIncome: 1_250_000,
  todayExpense: 340_000,
  monthlyIncome: 18_500_000,
  monthlyExpense: 7_850_000,
  currency: "VND",
};
